name: CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.40'
          # - '5.38'
          # - '5.36'
          # - '5.34'
          # - '5.32'
          # - '5.30'
          # - '5.28'
          # - '5.26'
          # - '5.24'
          # - '5.22'
          # - '5.20'
          # - '5.18'
          # - '5.16'
          # - '5.14'
          # - '5.12'
          # - '5.10'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm -n --installdeps .
      - name: Create a non-root user called "runner"
        run: adduser --disabled-password --gecos '' runner
      - name: Run Tests as non-root user "runner"
        run: |
          chown -R runner:runner .
          runuser runner -c 'cpanm --test-only -v .'
        env:
          SFDC_USER: ${{secrets.SFDC_USER}}
          SFDC_PASS: ${{secrets.SFDC_PASS}}
          SFDC_TOKEN: ${{secrets.SFDC_TOKEN}}
          SFDC_HOST: ${{secrets.SFDC_HOST}}
          SFDC_CLIENT_ID: ${{secrets.SFDC_CLIENT_ID}}
          SFDC_CLIENT_SECRET: ${{secrets.SFDC_CLIENT_SECRET}}
