name: macos
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
jobs:
  perl:
    runs-on: macOS-latest
    strategy:
      matrix:
        perl-version:
          - "5.42"
          - "5.16"
    steps:
      - uses: actions/checkout@v7
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm -n --installdeps .
      - run: id
      - name: Run Tests
        run: cpanm --test-only -v .
        env:
          SFDC_USER: ${{secrets.SFDC_USER}}
          SFDC_PASS: ${{secrets.SFDC_PASS}}
          SFDC_TOKEN: ${{secrets.SFDC_TOKEN}}
          SFDC_HOST: ${{secrets.SFDC_HOST}}
          SFDC_CLIENT_ID: ${{secrets.SFDC_CLIENT_ID}}
          SFDC_CLIENT_SECRET: ${{secrets.SFDC_CLIENT_SECRET}}
          SFDC_CC_CLIENT_ID: ${{secrets.SFDC_CC_CLIENT_ID}}
          SFDC_CC_CLIENT_SECRET: ${{secrets.SFDC_CC_CLIENT_SECRET}}
